/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SustainabilityRouteImport } from './routes/sustainability'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as NewsroomRouteImport } from './routes/newsroom'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InvestorsIndexRouteImport } from './routes/investors.index'
import { Route as InvestorsStockRouteImport } from './routes/investors.stock'
import { Route as InvestorsReportsRouteImport } from './routes/investors.reports'
import { Route as InvestorsGovernanceRouteImport } from './routes/investors.governance'
import { Route as InvestorsContactRouteImport } from './routes/investors.contact'
import { Route as InvestorsAnnouncementsRouteImport } from './routes/investors.announcements'

const SustainabilityRoute = SustainabilityRouteImport.update({
  id: '/sustainability',
  path: '/sustainability',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsroomRoute = NewsroomRouteImport.update({
  id: '/newsroom',
  path: '/newsroom',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorsIndexRoute = InvestorsIndexRouteImport.update({
  id: '/investors/',
  path: '/investors/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorsStockRoute = InvestorsStockRouteImport.update({
  id: '/investors/stock',
  path: '/investors/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorsReportsRoute = InvestorsReportsRouteImport.update({
  id: '/investors/reports',
  path: '/investors/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorsGovernanceRoute = InvestorsGovernanceRouteImport.update({
  id: '/investors/governance',
  path: '/investors/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorsContactRoute = InvestorsContactRouteImport.update({
  id: '/investors/contact',
  path: '/investors/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorsAnnouncementsRoute = InvestorsAnnouncementsRouteImport.update({
  id: '/investors/announcements',
  path: '/investors/announcements',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/careers': typeof CareersRoute
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/newsroom': typeof NewsroomRoute
  '/projects': typeof ProjectsRoute
  '/solutions': typeof SolutionsRoute
  '/sustainability': typeof SustainabilityRoute
  '/investors/announcements': typeof InvestorsAnnouncementsRoute
  '/investors/contact': typeof InvestorsContactRoute
  '/investors/governance': typeof InvestorsGovernanceRoute
  '/investors/reports': typeof InvestorsReportsRoute
  '/investors/stock': typeof InvestorsStockRoute
  '/investors/': typeof InvestorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/careers': typeof CareersRoute
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/newsroom': typeof NewsroomRoute
  '/projects': typeof ProjectsRoute
  '/solutions': typeof SolutionsRoute
  '/sustainability': typeof SustainabilityRoute
  '/investors/announcements': typeof InvestorsAnnouncementsRoute
  '/investors/contact': typeof InvestorsContactRoute
  '/investors/governance': typeof InvestorsGovernanceRoute
  '/investors/reports': typeof InvestorsReportsRoute
  '/investors/stock': typeof InvestorsStockRoute
  '/investors': typeof InvestorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/careers': typeof CareersRoute
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/newsroom': typeof NewsroomRoute
  '/projects': typeof ProjectsRoute
  '/solutions': typeof SolutionsRoute
  '/sustainability': typeof SustainabilityRoute
  '/investors/announcements': typeof InvestorsAnnouncementsRoute
  '/investors/contact': typeof InvestorsContactRoute
  '/investors/governance': typeof InvestorsGovernanceRoute
  '/investors/reports': typeof InvestorsReportsRoute
  '/investors/stock': typeof InvestorsStockRoute
  '/investors/': typeof InvestorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/careers'
    | '/company'
    | '/contact'
    | '/newsroom'
    | '/projects'
    | '/solutions'
    | '/sustainability'
    | '/investors/announcements'
    | '/investors/contact'
    | '/investors/governance'
    | '/investors/reports'
    | '/investors/stock'
    | '/investors/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/careers'
    | '/company'
    | '/contact'
    | '/newsroom'
    | '/projects'
    | '/solutions'
    | '/sustainability'
    | '/investors/announcements'
    | '/investors/contact'
    | '/investors/governance'
    | '/investors/reports'
    | '/investors/stock'
    | '/investors'
  id:
    | '__root__'
    | '/'
    | '/careers'
    | '/company'
    | '/contact'
    | '/newsroom'
    | '/projects'
    | '/solutions'
    | '/sustainability'
    | '/investors/announcements'
    | '/investors/contact'
    | '/investors/governance'
    | '/investors/reports'
    | '/investors/stock'
    | '/investors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CareersRoute: typeof CareersRoute
  CompanyRoute: typeof CompanyRoute
  ContactRoute: typeof ContactRoute
  NewsroomRoute: typeof NewsroomRoute
  ProjectsRoute: typeof ProjectsRoute
  SolutionsRoute: typeof SolutionsRoute
  SustainabilityRoute: typeof SustainabilityRoute
  InvestorsAnnouncementsRoute: typeof InvestorsAnnouncementsRoute
  InvestorsContactRoute: typeof InvestorsContactRoute
  InvestorsGovernanceRoute: typeof InvestorsGovernanceRoute
  InvestorsReportsRoute: typeof InvestorsReportsRoute
  InvestorsStockRoute: typeof InvestorsStockRoute
  InvestorsIndexRoute: typeof InvestorsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sustainability': {
      id: '/sustainability'
      path: '/sustainability'
      fullPath: '/sustainability'
      preLoaderRoute: typeof SustainabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsroom': {
      id: '/newsroom'
      path: '/newsroom'
      fullPath: '/newsroom'
      preLoaderRoute: typeof NewsroomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investors/': {
      id: '/investors/'
      path: '/investors'
      fullPath: '/investors/'
      preLoaderRoute: typeof InvestorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investors/stock': {
      id: '/investors/stock'
      path: '/investors/stock'
      fullPath: '/investors/stock'
      preLoaderRoute: typeof InvestorsStockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investors/reports': {
      id: '/investors/reports'
      path: '/investors/reports'
      fullPath: '/investors/reports'
      preLoaderRoute: typeof InvestorsReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investors/governance': {
      id: '/investors/governance'
      path: '/investors/governance'
      fullPath: '/investors/governance'
      preLoaderRoute: typeof InvestorsGovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investors/contact': {
      id: '/investors/contact'
      path: '/investors/contact'
      fullPath: '/investors/contact'
      preLoaderRoute: typeof InvestorsContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investors/announcements': {
      id: '/investors/announcements'
      path: '/investors/announcements'
      fullPath: '/investors/announcements'
      preLoaderRoute: typeof InvestorsAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CareersRoute: CareersRoute,
  CompanyRoute: CompanyRoute,
  ContactRoute: ContactRoute,
  NewsroomRoute: NewsroomRoute,
  ProjectsRoute: ProjectsRoute,
  SolutionsRoute: SolutionsRoute,
  SustainabilityRoute: SustainabilityRoute,
  InvestorsAnnouncementsRoute: InvestorsAnnouncementsRoute,
  InvestorsContactRoute: InvestorsContactRoute,
  InvestorsGovernanceRoute: InvestorsGovernanceRoute,
  InvestorsReportsRoute: InvestorsReportsRoute,
  InvestorsStockRoute: InvestorsStockRoute,
  InvestorsIndexRoute: InvestorsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
